services:
  db:
    image: pgvector/pgvector:pg16
    container_name: intellicrm_db
    restart: always
    environment:
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_pass
      POSTGRES_DB: intellicrm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: